
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'Ky\x8a\xfc\xfc~xa\xb3\xe8w\xb04\x82\x04\xff'
    
_lr_action_items = {'AND':([4,6,8,10,14,15,16,17,18,19,],[-8,11,11,-1,11,-7,11,-5,11,-6,]),'ALL':([0,2,5,7,9,11,12,13,],[1,1,1,1,1,1,1,1,]),'LBRACE':([0,2,5,7,9,11,12,13,],[2,2,2,2,2,2,2,2,]),'IMPLIES':([4,6,8,10,14,15,16,17,18,19,],[-8,12,12,-1,12,-7,12,-5,-4,-6,]),'RBRACE':([4,8,10,14,15,16,17,18,19,],[-8,15,-1,-2,-7,-3,-5,-4,-6,]),'EXISTS':([0,2,5,7,9,11,12,13,],[3,3,3,3,3,3,3,3,]),'BINDING':([1,3,],[7,9,]),'PREDICATE':([0,2,5,7,9,11,12,13,],[4,4,4,4,4,4,4,4,]),'NOT':([0,2,5,7,9,11,12,13,],[5,5,5,5,5,5,5,5,]),'OR':([4,6,8,10,14,15,16,17,18,19,],[-8,13,13,-1,13,-7,13,-5,13,-6,]),'$end':([4,6,10,14,15,16,17,18,19,],[-8,0,-1,-2,-7,-3,-5,-4,-6,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,5,7,9,11,12,13,],[6,8,10,14,16,17,18,19,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> NOT expression','expression',2,'p_expression_not','/Users/jhara_mac/Desktop/plato/env/lib/python2.7/site-packages/pylogic/logic.py',561),
  ('expression -> ALL BINDING expression','expression',3,'p_expression_forall_pred','/Users/jhara_mac/Desktop/plato/env/lib/python2.7/site-packages/pylogic/logic.py',565),
  ('expression -> EXISTS BINDING expression','expression',3,'p_expression_exists_pred','/Users/jhara_mac/Desktop/plato/env/lib/python2.7/site-packages/pylogic/logic.py',573),
  ('expression -> expression IMPLIES expression','expression',3,'p_expression_implies','/Users/jhara_mac/Desktop/plato/env/lib/python2.7/site-packages/pylogic/logic.py',581),
  ('expression -> expression AND expression','expression',3,'p_expression_and','/Users/jhara_mac/Desktop/plato/env/lib/python2.7/site-packages/pylogic/logic.py',586),
  ('expression -> expression OR expression','expression',3,'p_expression_or','/Users/jhara_mac/Desktop/plato/env/lib/python2.7/site-packages/pylogic/logic.py',590),
  ('expression -> LBRACE expression RBRACE','expression',3,'p_expression_group','/Users/jhara_mac/Desktop/plato/env/lib/python2.7/site-packages/pylogic/logic.py',594),
  ('expression -> PREDICATE','expression',1,'p_predicate','/Users/jhara_mac/Desktop/plato/env/lib/python2.7/site-packages/pylogic/logic.py',602),
]
